from __future__ import annotations

"""
fig_graphical_abstract -- required by LATAM. PNG, >=1328x531 px, >=400 dpi,
<=5 MB, generated by code.

Three blocks, left to right:
  1. Flow diagram: 30 datasets -> shared backbone -> 30 heads.
  2. Three bars: specialist (HC2), joint (C2), fine-tuned (C3) mean accuracy.
  3. A bracket showing the fine-tuning recovery closing most of the gap
     between joint and specialist, with the headline claim.

The "56%" is the recovery as a fraction of the gap, computed on the
20-dataset scope that has an HC2 reference (comparable scope throughout),
not the 30-dataset scope -- see three_condition_table.csv.
"""

import argparse
from pathlib import Path

import matplotlib.patches as mpatches
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

from src.figures.figure_style import PALETTE, apply_style

# LATAM's spec is a MINIMUM (>=1328x531px, >=400dpi, <=5MB) -- three panels
# of text at exactly 1328x531 has essentially no room to breathe. Using a
# larger canvas at the same aspect ratio comfortably clears the minimum.
WIDTH_PX, HEIGHT_PX = 1328 * 2, 531 * 2
DPI = 400


def _draw_flow(ax) -> None:
    ax.set_xlim(0, 10)
    ax.set_ylim(0, 10)
    ax.axis("off")

    n_show = 8
    ys = np.linspace(1.2, 8.8, n_show)
    for y in ys:
        ax.add_patch(mpatches.Rectangle((0.3, y - 0.25), 1.0, 0.5, facecolor=PALETTE[0], alpha=0.7, edgecolor="black", linewidth=0.4))
    ax.text(0.8, 9.5, "30 datasets", ha="center", fontsize=6.5)
    ax.text(0.8, 0.5, ".\n.\n.", ha="center", va="center", fontsize=6, linespacing=0.6)

    backbone_x0, backbone_x1 = 2.6, 5.6
    ax.add_patch(mpatches.FancyBboxPatch((backbone_x0, 3.0), backbone_x1 - backbone_x0, 4.0,
                                          boxstyle="round,pad=0.05", facecolor=PALETTE[2], alpha=0.75,
                                          edgecolor="black", linewidth=0.6))
    ax.text((backbone_x0 + backbone_x1) / 2, 5.0, "Shared\nbackbone", ha="center", va="center", fontsize=7, fontweight="bold")

    for y in ys:
        ax.plot([1.3, backbone_x0], [y, 5.0], color="black", linewidth=0.3, alpha=0.5)

    head_x0 = 6.4
    for y in ys:
        ax.add_patch(mpatches.Rectangle((head_x0, y - 0.22), 0.9, 0.44, facecolor=PALETTE[1], alpha=0.7, edgecolor="black", linewidth=0.4))
        ax.plot([backbone_x1, head_x0], [5.0, y], color="black", linewidth=0.3, alpha=0.5)
    ax.text(head_x0 + 0.45, 9.5, "30 heads", ha="center", fontsize=6.5)
    ax.text(head_x0 + 0.45, 0.5, ".\n.\n.", ha="center", va="center", fontsize=6, linespacing=0.6)


def _draw_three_bars(ax, three_condition_csv: Path) -> tuple[float, float, float, float]:
    df = pd.read_csv(three_condition_csv)
    hc2 = df.loc[(df["condition"] == "specialist") & (df["model"] == "HC2") & (df["scope"] == 20), "acc_mean"].iloc[0]
    joint = df.loc[(df["condition"] == "joint") & (df["model"] == "cnn") & (df["scope"] == 30), "acc_mean"].iloc[0]
    ft = df.loc[(df["condition"] == "finetuned") & (df["model"] == "cnn") & (df["scope"] == 30), "acc_mean"].iloc[0]
    # The displayed bars are the 30-dataset headline numbers, but the
    # recovered-fraction annotation needs HC2-comparable (20-dataset) scope
    # on both sides of the ratio, or it isn't a real percentage of the gap.
    joint_20 = df.loc[(df["condition"] == "joint") & (df["model"] == "cnn") & (df["scope"] == 20), "acc_mean"].iloc[0]
    ft_20 = df.loc[(df["condition"] == "finetuned") & (df["model"] == "cnn") & (df["scope"] == 20), "acc_mean"].iloc[0]
    recovered_fraction = (ft_20 - joint_20) / (hc2 - joint_20)

    labels = ["HC2", "Joint", "Tuned"]
    values = [hc2, joint, ft]
    colors = [PALETTE[3], PALETTE[0], PALETTE[1]]
    # Joint (blue) and Tuned (vermillion) sit close enough in grayscale
    # luminance that color alone doesn't distinguish them if printed without
    # color -- hatching does.
    hatches = [None, "//", "xx"]
    bars = ax.bar(labels, values, color=colors, edgecolor="black", linewidth=0.5, width=0.6, hatch=hatches)
    for bar, v in zip(bars, values):
        ax.text(bar.get_x() + bar.get_width() / 2, v + 0.03, f"{v:.3f}", ha="center", fontsize=11)

    ax.set_ylim(0, 1.12)
    ax.set_ylabel("Mean accuracy", fontsize=11)
    ax.tick_params(axis="x", labelsize=9)
    ax.tick_params(axis="y", labelsize=9)

    return hc2, joint, ft, recovered_fraction


def _draw_recovery_bracket(ax, hc2: float, joint: float, ft: float, recovered_fraction: float) -> None:
    ax.set_xlim(0, 1)
    ax.set_ylim(0, 1.12)
    ax.axis("off")

    x = 0.35
    ax.plot([x, x], [joint, hc2], color="grey", linewidth=1.5, zorder=1)
    # Same grayscale-distinguishability concern as the bars above: the joint
    # (blue) and fine-tuned (vermillion) tick marks get different marker/
    # linestyle so they don't rely on color alone.
    ax.plot([x - 0.05, x + 0.05], [joint, joint], color=PALETTE[0], linewidth=2.0,
             marker="o", markersize=4, markevery=[0, 1])
    ax.plot([x - 0.05, x + 0.05], [hc2, hc2], color=PALETTE[3], linewidth=2.0)
    ax.annotate("", xy=(x, ft), xytext=(x, joint),
                arrowprops=dict(arrowstyle="-|>", color=PALETTE[1], lw=3.0))
    ax.plot([x - 0.05, x + 0.05], [ft, ft], color=PALETTE[1], linewidth=2.0, linestyle="--")

    ax.text(x + 0.13, (joint + ft) / 2, f"{recovered_fraction * 100:.0f}% of\nthe gap\nrecovered",
            fontsize=10, va="center", ha="left", fontweight="bold")
    ax.text(0.5, 1.10, "Most of the cost\nof sharing is\nrecoverable",
            fontsize=11, ha="center", va="top", fontweight="bold", style="italic")


def run(
    per_dataset_csv: Path = Path("artifacts/results/per_dataset_results.csv"),
    baselines_csv: Path = Path("artifacts/results/baselines_reference.csv"),
    three_condition_csv: Path = Path("artifacts/results/three_condition_table.csv"),
    out_dir: Path = Path("figures"),
) -> plt.Figure:
    apply_style()
    fig = plt.figure(figsize=(WIDTH_PX / DPI, HEIGHT_PX / DPI), dpi=DPI)
    gs = fig.add_gridspec(1, 3, width_ratios=[0.85, 0.95, 1.05], wspace=0.65)

    ax_flow = fig.add_subplot(gs[0, 0])
    _draw_flow(ax_flow)

    ax_bars = fig.add_subplot(gs[0, 1])
    ax_bracket = fig.add_subplot(gs[0, 2])
    if three_condition_csv.exists():
        hc2, joint, ft, recovered_fraction = _draw_three_bars(ax_bars, three_condition_csv)
        _draw_recovery_bracket(ax_bracket, hc2, joint, ft, recovered_fraction)
    else:
        ax_bars.text(0.5, 0.5, "Run report stage first", ha="center", va="center", fontsize=6)
        ax_bars.axis("off")
        ax_bracket.axis("off")

    fig.subplots_adjust(left=0.06, right=0.98, top=0.82, bottom=0.22)

    out_dir.mkdir(parents=True, exist_ok=True)
    out_path = out_dir / "graphical_abstract.png"
    fig.savefig(out_path, dpi=DPI)

    size_mb = out_path.stat().st_size / (1024 * 1024)
    print(f"Wrote {out_path} ({WIDTH_PX}x{HEIGHT_PX}px @ {DPI}dpi, {size_mb:.2f} MB)")
    if size_mb > 5:
        print("[warn] exceeds LATAM's 5 MB limit for the graphical abstract")

    return fig


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser()
    p.add_argument("--per-dataset-csv", type=Path, default=Path("artifacts/results/per_dataset_results.csv"))
    p.add_argument("--baselines-csv", type=Path, default=Path("artifacts/results/baselines_reference.csv"))
    p.add_argument("--three-condition-csv", type=Path, default=Path("artifacts/results/three_condition_table.csv"))
    p.add_argument("--out-dir", type=Path, default=Path("figures"))
    return p.parse_args()


if __name__ == "__main__":
    args = parse_args()
    plt.close(run(args.per_dataset_csv, args.baselines_csv, args.three_condition_csv, args.out_dir))
